title: "Davide Di Giusto"
description: "Research Engineer @ Thales CortAIx Labs/R&T, Palaiseau, France"
theme: minima  


collections:
  projects:
    output: true
    permalink: /projects/:name/
    
nav:
  - title: "Home"
    url: "/"
  - title: "Publications"
    url: "/publications/"
  - title: "Projects"
    url: "/projects/"
